### ISSUE TITLE
I can't get the React application to run on development

### ISSUE THREAD

**Issue by ccalvarez** [ecstaticapps/demo.app#1]
Hi, thank you.

I´ve followed the instructions, started the application with `now dev`, but the React code is not being executed.

Besides, in production I get this error:

![image](https://user-images.githubusercontent.com/2665104/79711142-47326380-8284-11ea-8bc2-ef8206863071.png)

in this sentence

`const box = [
		...(loading ? { color: '#ffc40c', label: 'Loading...' } : {}),
		...(error ? { color: '#ff0000', label: `Error! ${error.message}` } : {}),
		...(data ? { color: '#6a007a', label: 'Data:' } : {}),
		...{ color: '#eee', label: 'Unknown error' }
	].find(x => x.color)[0]`
 
My Zeit deployment:  https://prisma-zeit.now.sh/
My repo:  https://github.com/ccalvarez/prisma-zeit

Thank you.

**Comment by heymartinadams** [comment]
Good catch! Fixed with https://github.com/ecstaticapps/demo.app/commit/a5e57fdf2cb1fa56cc629c10c8751358be8bf5de
